#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

node ./lib/write-tex.js > ./tex-outputs/calendar.tex && \
xelatex \
  -8bit \
  --output-directory ./tex-outputs \
  --halt-on-error \
  --enable-write18 --recorder \
  ./tex-outputs/calendar.tex && \
mv ./tex-outputs/calendar.pdf .
echo

