// Generated by CoffeeScript 1.7.1
(function() {
  var FI, O, data, get, misfit, settings, values;

  settings = {

    /* Choose your language: */
    language: 'nl_NL',

    /* Choose your styles: */
    styles: {
      weekdays: 'abbreviated',
      months: 'full',
      moon: 'plain',
      layout: 'plain'
    }
  };

  values = {
    weekdays: '${/data/translations/${/settings/language}/weekdays/${/settings/styles/weekdays}}',
    months: '${/data/translations/${/settings/language}/months/${/settings/styles/months}}',
    moon: '${/data/moon/${/settings/styles/moon}}',
    layout: '${/data/layouts/${/settings/styles/layout}}'
  };

  data = {
    moon: {
      unicode: ['⬤', '◐', '◯', '◑'],
      plain: ['\\newmoon', '\\rightmoon', '\\fullmoon', '\\leftmoon']
    },
    translations: {
      nl_NL: {
        weekdays: {
          full: ['maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag', 'zondag'],
          abbreviated: ['ma', 'di', 'wo', 'do', 'vr', 'za', 'zo']
        },
        months: {
          full: ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"],
          abbreviated: ["jan", "feb", "maart", "apr", "mei", "juni", "juli", "aug", "sept", "oct", "nov", "dec"]
        }
      },
      en_US: {
        weekdays: {
          full: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
          abbreviated: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su']
        },
        months: {
          full: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
          abbreviated: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec"]
        }
      },
      de_DE: {
        weekdays: {
          full: ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'],
          abbreviated: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So']
        },
        months: {
          full: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
          abbreviated: ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sept", "Okt", "Nov", "Dez"]
        }
      }
    },

    /* All measurements in mm (this may change) */
    layouts: {
      plain: {
        margins: {
          outer: 10,
          top: 12
        },
        month: {
          even: {
            align: {
              x: 'left',
              y: 'baseline'
            },
            position: {
              x: '${/data/layouts/plain/margins/outer}',
              y: '${/data/layouts/plain/margins/top}'
            }
          },
          odd: {
            align: {
              x: 'right',
              y: 'baseline'
            },
            position: {
              x: 118,
              y: 0
            }
          }
        }
      }
    }
  };

  get = function(locator_or_crumbs, fallback) {
    return FI.get(O, locator_or_crumbs, fallback);
  };

  FI = require('coffeenode-fillin');

  module.exports = O = {};

  misfit = {};

  O['settings'] = settings;

  O['values'] = values;

  O['data'] = data;

  O['get'] = get;

  FI.fill_in(O);

}).call(this);
