// Generated by CoffeeScript 1.7.1
(function() {
  var FI, O, data, get, misfit, settings, values;

  settings = {

    /* Choose your language: */
    language: 'nl_NL',

    /* Choose your styles: */
    styles: {
      weekdays: 'abbreviated',
      months: 'full',
      moon: 'plain',
      layout: 'plain'
    }
  };

  values = {
    moon: '${/data/moon/${/settings/styles/moon}}',
    layout: '${/data/layouts/${/settings/styles/layout}}'
  };

  data = {
    tides: {
      'min-l-height': null,
      'max-l-height': null,
      'min-h-height': null,
      'max-h-height': null
    },
    date: {
      timezone: 'Europe/Amsterdam',
      'raw-format': 'DD/MM/YYYY HH:mm'
    },
    moon: {
      'quarter-by-phases': {
        'NM': 0,
        'EK': 1,
        'VM': 2,
        'LK': 3
      },
      unicode: ['⬤', '◐', '◯', '◑'],
      plain: ['\\newmoon', '\\rightmoon', '\\fullmoon', '\\leftmoon']
    },
    xxx: {
      'AUKFPFM': 'Aukfield platform',
      'BAALHK': 'Baalhoek',
      'BATH': 'Bath',
      'BEERKNL': 'Beerkanaal',
      'BERGSDSWT': 'Bergse Diepsluis west',
      'BORSSLE': 'Borssele',
      'BRESKS': 'Breskens',
      'BROUWHVSGT02': 'Brouwershavensche Gat 02',
      'BROUWHVSGT08': 'Brouwershavensche Gat 08',
      'CADZD': 'Cadzand',
      'DELFZL': 'Delfzijl',
      'DENHDR': 'Den Helder',
      'DENOVBTN': 'Den Oever',
      'DINTHVN': 'Dintelhaven',
      'DORDT': 'Dordrecht',
      'EEMHVN': 'Eemhaven',
      'EEMSHVN': 'Eemshaven',
      'EURPFM': 'Euro platform',
      'EURPHVN': 'Europahaven',
      'GEULHVN': 'Geulhaven',
      'GOIDSOD': 'Goidschalxoord',
      'GOUDBG': 'Gouda brug',
      'HAGSBNDN': 'Hagestein beneden',
      'HANSWT': 'Hansweert',
      'HARLGN': 'Harlingen',
      'HARMSBG': 'Harmsenbrug',
      'HARTBG': 'Hartelbrug',
      'HARTHVN': 'Hartelhaven',
      'HARTKWT': 'Hartel-Kuwait',
      'HARVT10': 'Haringvliet 10',
      'HEESBN': 'Heesbeen',
      'HELLVSS': 'Hellevoetsluis',
      'HOEKVHLD': 'Hoek van Holland',
      'HUIBGT': 'Huibertgat',
      'IJMDBTHVN': 'IJmuiden',
      'K13APFM': 'K13A platform',
      'KATSBTN': 'Kats',
      'KEIZVR': 'Keizersveer',
      'KORNWDZBTN': 'Kornwerderzand',
      'KRAMMSZWT': 'Krammersluizen west',
      'KRIMPADIJSL': 'Krimpen aan de IJssel',
      'KRIMPADLK': 'Krimpen aan de Lek',
      'LAUWOG': 'Lauwersoog',
      'LICHTELGRE': 'Lichteiland Goeree',
      'LITHDP': 'Lith dorp',
      'MAASSS': 'Maassluis',
      'MARLGT': 'Marollegat',
      'MOERDK': 'Moerdijk',
      'NES': 'Nes',
      'NIEUWSTZL': 'Nieuwe Statenzijl',
      'NOORDWMPT': 'Meetpost Noordwijk',
      'OOSTSDE04': 'Oosterschelde 04',
      'OOSTSDE11': 'Oosterschelde 11',
      'OOSTSDE14': 'Oosterschelde 14',
      'OUDSD': 'Oudeschild',
      'OVLVHWT': 'Overloop van Hansweert',
      'PARKSS': 'Parksluis',
      'PETTZD': 'Petten zuid',
      'RAKND': 'Rak noord',
      'ROOMPBNN': 'Roompot binnen',
      'ROOMPBTN': 'Roompot buiten',
      'ROTTDM': 'Rotterdam',
      'ROZBSSNZDE': 'Rozenburgsesluis noordzijde',
      'SCHAARVDND': 'Schaar van de Noord',
      'SCHEURHVN': 'Scheurhaven',
      'SCHEVNGN': 'Scheveningen',
      'SCHIERMNOG': 'Schiermonnikoog',
      'SCHOONHVN': 'Schoonhoven',
      'SPIJKNSE': 'Spijkenisse',
      'STAVNSE': 'Stavenisse',
      'STELLDBTN': 'Haringvlietsluizen',
      'SUURHBNZDE': 'Suurhoffbrug noordzijde',
      'TERNZN': 'Terneuzen',
      'TERSLNZE': 'Terschelling Noordzee',
      'TEXNZE': 'Texel Noordzee',
      'VLAARDGN': 'Vlaardingen',
      'VLAKTVDRN': 'Vlakte van de Raan',
      'VLIELHVN': 'Vlieland haven',
      'VLISSGN': 'Vlissingen',
      'VURN': 'Vuren',
      'WALSODN': 'Walsoorden',
      'WERKDBTN': 'Werkendam buiten',
      'WESTKPLE': 'Westkapelle',
      'WESTTSLG': 'West-Terschelling',
      'WIERMGDN': 'Wierumergronden',
      'YERSKE': 'Yerseke'
    },

    /* All measurements in mm (this may change) */
    layouts: {
      plain: {
        margins: {
          outer: 10,
          top: 12
        },
        month: {
          even: {
            align: {
              x: 'left',
              y: 'baseline'
            },
            position: {
              x: '${/data/layouts/plain/margins/outer}',
              y: '${/data/layouts/plain/margins/top}'
            }
          },
          odd: {
            align: {
              x: 'right',
              y: 'baseline'
            },
            position: {
              x: 118,
              y: 0
            }
          }
        }
      }
    }
  };

  get = function(locator_or_crumbs, fallback) {
    return FI.get(O, locator_or_crumbs, fallback);
  };

  FI = require('coffeenode-fillin');

  module.exports = O = {};

  misfit = {};

  O['settings'] = settings;

  O['values'] = values;

  O['data'] = data;

  O['get'] = get;

  FI.fill_in(O);

}).call(this);
